source 'https://rubygems.org'
ruby "1.9.3"
if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

gem 'sinatra'

group :development, :test do
  gem 'rspec'
  gem 'cucumber'
  gem 'webrat'
end
